spring:
  mvc:
    log-request-details: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  jpa:
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            #            issuer-uri: http://localhost:8080/realms/house-share
            issuer-uri: http://192.168.1.150:8080/realms/house-share
        registration:
          house-share-server:
            provider: keycloak
            client-id: house-share-server
            client-secret: TfvbQdtekYanX686RgkbUhzToCefcS6Y
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            #            redirect-uri: http://localhost:${server.port}/login/oauth2/code/house-share-server
            redirect-uri: http://192.168.1.150:${server.port}/login/oauth2/code/house-share-server

          house-share-app:
            provider: keycloak
            client-id: house-share-app
            client-secret: LeLeiJX2qUrdGB3DapC05zpInFEMndBR
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: app://lol.terabrendon.houseshare2/login/oauth2

logging:
  level:
    root: info
    org.springframework.web: debug
    # Explain why @PreAuthorize checks fail
    org.springframework.security.authorization: debug
    com.github.brendonmendicino.houseshareserver.service.AuthorizationService: debug
    com.github.brendonmendicino.houseshareserver.service.SignedUrlService: debug
    # SQL statements (formatted by `hibernate.format_sql`) and their bound parameters
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'

  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s # Sampling for development
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: http
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
          transport: http

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    csrf:
      enabled: true

server:
  port: 9090

#debug: true