spring:
  config:
    activate:
      on-profile: dev

  mvc:
    log-request-details: true

  jpa:
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.1.150:8080/realms/house-share
        registration:
          house-share-server:
            provider: keycloak
            client-id: house-share-server
            client-secret: TfvbQdtekYanX686RgkbUhzToCefcS6Y
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.1.150:${server.port}/login/oauth2/code/house-share-server

          house-share-app:
            provider: keycloak
            client-id: house-share-app
            client-secret: LeLeiJX2qUrdGB3DapC05zpInFEMndBR
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: app://lol.terabrendon.houseshare2/login

service:
  paddle:
    url: http://localhost:8000

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s # Sampling for development
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: grpc
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
          transport: grpc

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    csrf:
      enabled: true

server:
  port: 9090

debug: true