spring:
  application:
    name: house-share-server

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          additional-models:
            - qwen3.5:0.8b
            - qwen3.5:2b
      chat:
        options:
          model: qwen3.5:0.8b
          temperature: 1.0
          top-p: 1.0
          top-k: 20
          min-p: 0.0
          presence-penalty: 2.0
          repeat-penalty: 1.0
          think-option: "false"

  jackson:
    use-jackson2-defaults: true

springdoc:
  swagger-ui:
    enabled: false
