CREATE TABLE app_group
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    image_url TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_appgroup PRIMARY KEY (id)
);

CREATE TABLE app_group_user
(
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_app_group_user PRIMARY KEY (group_id, user_id)
);

CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    sub        VARCHAR(255),
    picture  TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE expense
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category         SMALLINT,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(5000),
    owner_id    BIGINT       NOT NULL,
    payer_id    BIGINT       NOT NULL,
    group_id         BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE expense_part
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_amount    BIGINT                                  NOT NULL,
    part_of_id     BIGINT NOT NULL,
    member_part_id BIGINT NOT NULL,
    CONSTRAINT pk_expensepart PRIMARY KEY (id)
);

CREATE TABLE group_member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    picture    TEXT,
    group_id   BIGINT                                  NOT NULL,
    user_id    BIGINT,
    CONSTRAINT pk_groupmember PRIMARY KEY (id)
);

CREATE TABLE shopping_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    amount             INTEGER                                 NOT NULL,
    price              BIGINT,
    priority           SMALLINT,
    checkoff_timestamp TIMESTAMP WITHOUT TIME ZONE,
    checking_member_id BIGINT,
    owner_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_shoppingitem PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_sub UNIQUE (sub);

CREATE INDEX idx_57bf796ac4e421512a354482e ON app_user (sub);

ALTER TABLE expense_part
    ADD CONSTRAINT FK_EXPENSEPART_ON_MEMBERPART FOREIGN KEY (member_part_id) REFERENCES group_member (id);

ALTER TABLE expense_part
    ADD CONSTRAINT FK_EXPENSEPART_ON_PARTOF FOREIGN KEY (part_of_id) REFERENCES expense (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_GROUP FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_OWNER FOREIGN KEY (owner_id) REFERENCES group_member (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_PAYER FOREIGN KEY (payer_id) REFERENCES group_member (id);

ALTER TABLE group_member
    ADD CONSTRAINT FK_GROUPMEMBER_ON_GROUP FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE group_member
    ADD CONSTRAINT FK_GROUPMEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_CHECKINGMEMBER FOREIGN KEY (checking_member_id) REFERENCES group_member (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_GROUP FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES group_member (id);

ALTER TABLE app_group_user
    ADD CONSTRAINT fk_appgrouse_on_app_group FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE app_group_user
    ADD CONSTRAINT fk_appgrouse_on_app_user FOREIGN KEY (user_id) REFERENCES app_user (id);