CREATE TABLE app_group
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_appgroup PRIMARY KEY (id)
);

CREATE TABLE app_group_app_user
(
    groups_id BIGINT NOT NULL,
    users_id  BIGINT NOT NULL,
    CONSTRAINT pk_app_group_app_user PRIMARY KEY (groups_id, users_id)
);

CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    sub        VARCHAR(255),
    picture    bytea,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE expense
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category         SMALLINT,
    title            VARCHAR(255),
    description      VARCHAR(255),
    owner_id         BIGINT,
    payer_id         BIGINT,
    group_id         BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE expense_part
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_amount  BIGINT                                  NOT NULL,
    part_of_id   BIGINT,
    user_part_id BIGINT,
    CONSTRAINT pk_expensepart PRIMARY KEY (id)
);

CREATE TABLE shopping_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    amount             INTEGER                                 NOT NULL,
    price              BIGINT,
    priority           SMALLINT,
    checkoff_timestamp TIMESTAMP WITHOUT TIME ZONE,
    checking_user_id   BIGINT,
    owner_id           BIGINT,
    group_id           BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_shoppingitem PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_sub UNIQUE (sub);

CREATE INDEX idx_57bf796ac4e421512a354482e ON app_user (sub);

ALTER TABLE expense_part
    ADD CONSTRAINT FK_EXPENSEPART_ON_PARTOF FOREIGN KEY (part_of_id) REFERENCES expense (id);

ALTER TABLE expense_part
    ADD CONSTRAINT FK_EXPENSEPART_ON_USERPART FOREIGN KEY (user_part_id) REFERENCES app_user (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_GROUP FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_OWNER FOREIGN KEY (owner_id) REFERENCES app_user (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_PAYER FOREIGN KEY (payer_id) REFERENCES app_user (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_CHECKINGUSER FOREIGN KEY (checking_user_id) REFERENCES app_user (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_GROUP FOREIGN KEY (group_id) REFERENCES app_group (id);

ALTER TABLE shopping_item
    ADD CONSTRAINT FK_SHOPPINGITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES app_user (id);

ALTER TABLE app_group_app_user
    ADD CONSTRAINT fk_appgroappuse_on_app_group FOREIGN KEY (groups_id) REFERENCES app_group (id);

ALTER TABLE app_group_app_user
    ADD CONSTRAINT fk_appgroappuse_on_app_user FOREIGN KEY (users_id) REFERENCES app_user (id);